version: "3"
services:
  api:
    restart: always
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor/
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/uploads/:/var/www/uploads/
    networks:
      - app-network
    depends_on:
      - db

  db:
    container_name: db
    image: mariadb
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Bangkok
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS app;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    networks:
      - app-network

  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    links:
      - db:db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
